import "./styles/globals.css";
// import { Providers } from "@/components/providers";
// import { Footer } from "@/components/Footer/Footer";
import { Providers } from "./providers";
import Link from 'next/link'

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // get router
  // console.log('Router', Router);
  return (
    <html lang="en">
      <body className="w-full h-screen justify-center items-center bg-untile-white">
        <Providers>
          {/* header with bottom border */}
          <header
            className="flex w-full h-16 items-center justify-center border-b-2 border-untile-gray space-x-6"
          >
            <Link
              href="/calculator"
              className="text-untile-gray flex flex-col justify-center
              hover:border-b-2 hover:border-untile-blue duration-300 ease-in-out"
              style={{ height: "calc(100% + 4px)" }}
            >
              CRYPTO CALCULATOR
            </Link>
            <Link
              href="/tickers"
              className="text-untile-gray flex flex-col justify-center
              hover:border-b-2 hover:border-untile-blue duration-300 ease-in-out"
              style={{ height: "calc(100% + 4px)" }}
            >
              TICKERS
            </Link>
            {/* <Link href="/">
              <a className="text-white">About</a>
            </Link>  */}
          </header>
          <main className="flex flex-col h-1/2   items-center justify-evenly p-24">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
